[package]
name = "image_fmt"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jpeg-decoder = "0.3.0"
png = "0.17.7"
tiff = "0.9.1"
fast_image_resize = "3.0.3"
