[package]
name = "job_queue"
version = "0.3.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scheduled-thread-pool = "0.2"

[dependencies.shared_data]
path = "../shared_data"
