name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Install Ubuntu Dependencies
        run: sudo apt-get install libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev

      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Build and test
      - run: cargo +stable build
      - run: cargo +stable test
      - run: cargo +stable bench --no-run
