name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Install Ubuntu Dependencies
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev

      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # Build and test, and make sure benchmarks build.
      - run: cargo +stable test --all && cargo +stable bench --profile=dev --no-run --all
