name: ci

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Install Ubuntu Dependencies
        run: apt-get install libgtk-3-dev
      
      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Build and test
      - run: cargo +stable test
      - run: cargo +stable bench --no-run
      - run: cargo +stable build --release

  pre-release-ubuntu-macos:
    name: Pre Release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}   

    steps:
      - name: Install Ubuntu Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: apt-get install libgtk-3-dev

      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Build
      - run: cargo +stable build --release

      # Release
      - name: Release Ubuntu/MacOS
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest' }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development-release"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/hdri_merge
            target/release/images_to_sensor_response
      - name: Release Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development-release"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/hdri_merge.exe
            target/release/images_to_sensor_response.exe
