name: release
on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  executable_names: hdri_merge

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        build: [x86_64-linux, x86_64-macos, x86_64-windows]
        include:
        - build: x86_64-linux
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-gnu
          cross: false
        - build: x86_64-macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
          cross: false
        - build: x86_64-windows
          os: windows-2019
          rust: stable
          target: x86_64-pc-windows-msvc
          cross: false

    steps:
      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --target ${{ matrix.target }}
      
      - name: Strip release binary (linux and macos)
        shell: bash
        run: |
          if [[ ! "${{ matrix.os }}" =~ "windows" ]]; then
            for executable in ${executable_names}; do
              strip "target/${{ matrix.target }}/release/${executable}"
            done
          fi
          
      
      - name: Upload files for packaging
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" =~ "windows" ]]; then
            exe=".exe"
          fi
          mkdir dist
          for executable in ${executable_names}; do
            cp "target/${{ matrix.target }}/release/${executable}${exe}" "dist/"
          done
          cp LICENSE.md README.md "dist/"
      
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: files-${{ matrix.build }}
          path: dist
  
  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      
      - run: ls -al files-*
      
      - name: Calculate tag name
        run: |
          name=dev
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            name=${GITHUB_REF:10}
          fi
          echo ::set-output name=val::$name
          echo TAG=$name >> $GITHUB_ENV
        id: tagname
      
      - name: Build archive
        shell: bash
        run: |
          set -ex

          rm -rf tmp
          mkdir tmp
          mkdir dist

          for dir in files-* ; do
              platform=${dir#"files-"}
              if [[ $platform =~ "windows" ]]; then
                  exe=".exe"
              fi
              pkgname=image_tools-$TAG-$platform
              mkdir tmp/$pkgname
              mv ${dir}/* tmp/$pkgname/
              for executable in ${executable_names}; do
                chmod +x tmp/$pkgname/${executable}${exe}
              done

              if [ "$exe" = "" ]; then
                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
              else
                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
              fi
          done

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ steps.tagname.outputs.val }}
          overwrite: true
          prerelease: false
