name: release
on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  EXECUTABLE_NAMES: hdri_merge lut_maker ocio_maker

jobs:
  # Because github actions don't let us set dynamic
  # environment variables.
  env2:
    name: Get misc info
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.vars.outputs.HASH }}
      date: ${{ steps.vars.outputs.DATE }}
      date_hash_tag: ${{ steps.vars.outputs.DATE_HASH_TAG }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get info
        id: vars
        shell: bash
        run: |
          BUILD_HASH=$(git rev-parse --short "$GITHUB_SHA")
          BUILD_DATE=$(date +'%Y-%m-%d')
          BUILD_DATE_HASH_TAG=$(echo $BUILD_DATE | sed -e 's/-/_/g')-${BUILD_HASH}
          echo "::set-output name=HASH::$BUILD_HASH"
          echo "::set-output name=DATE::$BUILD_DATE"
          echo "::set-output name=DATE_HASH_TAG::$BUILD_DATE_HASH_TAG"

  build:
    name: Build
    needs: [env2]
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        build: [x86_64-linux, x86_64-macos, x86_64-windows]
        include:
        - build: x86_64-linux
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-gnu
          cross: false
        - build: x86_64-macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
          cross: false
        - build: x86_64-windows
          os: windows-2019
          rust: stable
          target: x86_64-pc-windows-msvc
          cross: false

    steps:
      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev wget

      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Build release binaries
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" =~ "ubuntu" ]]; then
            # Build appimages on Ubuntu.
            wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
            mv appimagetool-x86_64.AppImage appimagetool
            chmod +x appimagetool
            sudo mv appimagetool /usr/local/bin/
            cargo +${{ matrix.rust }} install --git https://github.com/cessen/cargo-appimage.git --branch custom
            cargo +${{ matrix.rust }} appimage --target=${{ matrix.target }}
          else
            cargo +${{ matrix.rust }} build --release --target=${{ matrix.target }}
          fi
      
      - name: Strip release binary (macos)
        shell: bash
        run: |
          if [[ ! "${{ matrix.os }}" =~ ("windows"|"ubuntu") ]]; then
            for executable in ${EXECUTABLE_NAMES}; do
              strip "target/${{ matrix.target }}/release/${executable}"
            done
          fi
          
      - name: Upload files for packaging
        shell: bash
        run: |
          mkdir dist
          for executable in ${EXECUTABLE_NAMES}; do
            if [[ "${{ matrix.os }}" =~ "windows" ]]; then
              cp "target/${{ matrix.target }}/release/${executable}.exe" "dist/"
            elif [[ "${{ matrix.os }}" =~ "ubuntu" ]]; then
              cp "${executable}"*.AppImage "dist/${executable}.AppImage"
            else
              cp "target/${{ matrix.target }}/release/${executable}" "dist/"
            fi
          done
          cp LICENSE.md README.md "dist/"
      
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: files-${{ matrix.build }}
          path: dist
  
  publish:
    name: Publish
    needs: [env2, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      
      - run: ls -al files-*
      
      - name: Calculate tag name
        run: |
          name=dev
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            name=${GITHUB_REF:10}
          fi
          echo ::set-output name=val::$name
          echo TAG=$name >> $GITHUB_ENV
        id: tagname
      
      - name: Build archive
        shell: bash
        run: |
          set -ex

          rm -rf tmp
          mkdir tmp
          mkdir dist

          for dir in files-* ; do
              platform=${dir#"files-"}
              pkgname=etf_image_tools-$TAG-$platform
              mkdir tmp/$pkgname
              mv ${dir}/* tmp/$pkgname/
              for executable in ${EXECUTABLE_NAMES}; do
                if [[ $platform =~ "windows" ]]; then
                  chmod +x tmp/$pkgname/${executable}.exe
                elif [[ $platform =~ "linux" ]]; then
                  chmod +x tmp/$pkgname/${executable}.AppImage
                else
                  chmod +x tmp/$pkgname/${executable}
                fi
              done

              if [[ $platform =~ "windows" ]]; then
                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
              else
                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
              fi
          done

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ steps.tagname.outputs.val }}
          overwrite: true
          prerelease: false
